export const mockProducts = [
  {
    id: "1",
    title: "Curso Completo de React + TypeScript",
    producer: "Dev Academy",
    price: 29700,
    coverColor: "hsl(158, 40%, 20%)",
    type: "lms" as const,
    sales: 1247,
    commission: 40,
  },
  {
    id: "2",
    title: "Pack de Templates para Landing Pages",
    producer: "Design Studio",
    price: 4900,
    coverColor: "hsl(210, 40%, 20%)",
    type: "download" as const,
    sales: 3890,
    commission: 30,
  },
  {
    id: "3",
    title: "Mentoria de Marketing Digital 1:1",
    producer: "Growth Lab",
    price: 99900,
    coverColor: "hsl(280, 40%, 20%)",
    type: "lms" as const,
    sales: 89,
    commission: 25,
  },
  {
    id: "4",
    title: "E-book: Copywriting que Converte",
    producer: "Copy Masters",
    price: 3900,
    coverColor: "hsl(38, 40%, 20%)",
    type: "download" as const,
    sales: 7650,
    commission: 50,
  },
  {
    id: "5",
    title: "Curso de Python para Data Science",
    producer: "Data Lab BR",
    price: 19900,
    coverColor: "hsl(200, 40%, 20%)",
    type: "lms" as const,
    sales: 2100,
    commission: 35,
  },
  {
    id: "6",
    title: "Kit de Presets para Lightroom",
    producer: "Photo Pro",
    price: 7900,
    coverColor: "hsl(340, 40%, 20%)",
    type: "download" as const,
    sales: 5430,
    commission: 45,
  },
  {
    id: "7",
    title: "Automação com N8N e IA",
    producer: "Auto Flow",
    price: 14900,
    coverColor: "hsl(170, 40%, 18%)",
    type: "lms" as const,
    sales: 670,
    commission: 30,
  },
  {
    id: "8",
    title: "Planilha Financeira Completa",
    producer: "Finance Tools",
    price: 2900,
    coverColor: "hsl(120, 30%, 18%)",
    type: "download" as const,
    sales: 12300,
    commission: 50,
  },
];
